### ISSUE TITLE
Error on typescript execution 

### ISSUE THREAD

**Issue by TerenceU** [JacksonKearl/vscode-handydandy-notebook#5]
When trying to execute some typescript I'm getting this error:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/22168241/167586745-81aa773a-377e-47f4-9d10-ba6ca139c21e.png">

I have default settings:
<img width="178" alt="image" src="https://user-images.githubusercontent.com/22168241/167587295-8b1bb16a-a7f4-4703-bcf0-0e5abc6aca68.png">

**Comment by Okrekso** [comment]
The same. Command in CMD works fine but via notebook shows ENOENT

**Comment by JacksonKearl** [comment]
What platform? Can you try running the span via a node directly? ie:

```
const cp = require('child_process')
cp.spawn('ts-node -T --skip-project -e "console.log(\'hello\')"', {cwd: '...some path...'})
process.on('error', (err) => {
console.error(err)
})
process.stdout.on('data', (data: Buffer) => {
	console.log(data.toString());
});
process.stderr.on('data', (data: Buffer) => {
	console.log(data.toString());
});
```

that's basically all the extension is doing

**Comment by TerenceU** [comment]
I'm on vs-code:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/22168241/167675083-dec12caf-ee8a-4ad2-b64b-8fb2d5827105.png">

I get the same error.
But if i execute the command like this it works. 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/22168241/167675796-e80683d9-22aa-4223-ad93-5db71ca01e9c.png">

**Comment by JacksonKearl** [comment]
Some ideas: 
1. see where you ts-node is being added to your path (some .rc file that isn't being run?)
2. provide an absolute path to your ts-node executable

**Comment by TerenceU** [comment]
I'm using windows and ts-node was not on the path, but even including the ts-node executable has changed the result I still get:
Error: spawn ts-node ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by JacksonKearl** [comment]
I see.. well if you can find a way to run TS using the node.js `child_process` module I can look into supporting it, but unfortunately I do not have capacity to debug this.

**Comment by brunnerh** [comment]
On Windows, executables installed via NPM work via `.cmd` wrapper files. When typing `ts-node` into a prompt it will implicitly search for files with executable extensions (like `exe`, `bat` or `cmd`) and execute those. Spawning a child process via Node does not have this magic.
So `ts-node` could be run by adjusting the dispatch settings like this:
```jsonc
"typescript": [
  "ts-node.cmd",
  // ...
```

Unfortunately this still does not quite work because the [code spawning the processes](https://github.com/JacksonKearl/vscode-handydandy-notebook/blob/d9bcc39c8347af987513bfb1e55aec1ee6a3478f/src/OmniExecutor.ts#L33) adds line breaks before and after the code:
```ts
commands[language][1].map(arg => arg.replace(/\$\{code\}/, `\n${text}\n`))
```
The CMD file appears to not process this correctly. The command terminates at the line break and you get an error that the code for the `-e` argument is missing. Then again, the cells themselves may contain additional line breaks.

As a workaround to this issue, one can call the Node executable instead and provide a path to the entry file of a `ts-node` installation:
```jsonc
"typescript": [
  "node",
  [
    "<FULL-PATH-HERE>/node_modules/ts-node/dist/bin.js",
    "-T",
    "--skip-project",
    "-e",
    "${code}"
  ]
]
```

**Comment by TerenceU** [comment]
Wow! It worked like a bijoux! Thanks a lot @brunnerh!
