### ISSUE TITLE
Add an option to write the cell code to a temporary file

### ISSUE THREAD

**Issue by ghost** [JacksonKearl/vscode-handydandy-notebook#6]
Hello,

your plugin is simple and works really good.
But i've trouble integrating some interpreters, that don't have a command argument for executing code directly (`-e`, `-c`).
They can just run files given as arguments.

Can you add a simple feature for that? Something that i can configure my interpreters like this:
```json
"handydandy-notebook.dispatch": {
  "C": [
    "tcc",
    ["-run", "${code:tempFile}"]  
]
}
```

If you find the string `${code:tempFile}` as argument, replace it with something like: `path.join(os.tmpdir(), Date.now(), language)` and write the `cell.document.getText()` to that file.

If you find that useful, i can also try to implement that and give you a PR for this.

Thank and greetings,
Steven

**Comment by JacksonKearl** [comment]
It's something I've considered, though I do want to keep the extension as simple as possible and the second we start creating files we need to worry about things like: 
- cleaning them up (especially in the case of errors & long running commands)
- where they're located (some path relative to the notebook? workspace? extension? and what about if the notebook is unsaved?)
- what name they're given (some utils like to be particular about precise file extensions)
- permissions
- etc. 

I'm not fully against the idea, but it does have potential to be a can of worms.

It should be possible to construct a shell script that accepts standard input and writes it to a file in a location of your choosing then runs an executable of your choosing against that, have you looked into such an approach?

For instance:
`run-tcc.sh`:
```sh
#!/bin/sh
echo "$1" > ./tmpfile.c
tcc -run ./tmpfile.c
```

`handydandy-notebook.dispatch`:
```
    ...
    "c": [
      "/Users/jkearl/Downloads/tcc-0.9.27/stdin-to-tcc.sh",
      [
        "${code}"
      ]
    ],
    ...
```

We could provide a `${cell-id}`or `${execution-id}` expansion of some sort to help when executing multiple cells at once.

**Comment by HomemadeToast57** [comment]
It would be really neat to be able to create a temp file for each language so we can keep the same context between cells of the same language. Maybe even an option to give a name or id to each context of each language too so you can order stuff around. I think this really increases the number of use cases for this already great extension. Perhaps once I finish finals at university I'd be interested in collaborating and implementing this :). We could even write a parser that reads through and looks for context ids and combines all the code blocks by context behind the scenes (no creating files, just modifying current).

**Comment by JacksonKearl** [comment]
@HomemadeToast57 this is also something I've considered. Inspiration dates back to Knuth's concept of Literate Programming, in which blocks of code are written out in some intuitive sequence, then concatenated together in arbitrary orderings using a type of macro expression to form the final product to be delivered to the interpreter. Take for instance this wc implementation: https://github.com/zyedidia/Literate/blob/master/examples/wc.lit

In handy dandy notebook, that program may look something like:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/8586769/168139664-ccf4794e-108a-4b4d-b8fc-5c5fd7388989.png">

<summary> Full code:
<details>
# Word Count Program

Here, is an overview of the file `wc.c` that is defined by this Literate program:

```c
@{Header files to include}
@{Preprocessor definitions}
@{Global variables}
@{Functions}
@{The main program}
```

### Header files to include

We must include the standard I/O definitions, since we want to send formatted output to *stdout* and *stderr*.

```c
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
```

### Preprocessor definitions

We define various codes to represent different exist conditions of the program

```c
#define OK 1    /* status code for successful run */
#define usage_error 1    /* status code for improper syntax */
#define cannot_open_file 2    /* status code for file access error */
```

### Global variables
The `status` variable will tell the operating system if the run was successful or not,
and `prog_name` is used in case there’s an error message to be printed.

```c
int status = OK;    /* exit status of command, initially OK */
char *prog_name;    /* who we are */
```

### The main program

Now we come to the general layout of the `main()` function.

```c
int main(int argc, char **argv)
{
    @{Variables local to main}
    prog_name = argv[0];
    @{Set up option selection}
    @{Process all the files}
    @{Print the grand totals if there were multiple files}
    return status;
}
```

### Variables local to main

```c
int file_count;    /* how many files there are */
char *which;    /* which counts to print */
int silent = 0;    /* nonzero if the silent option was selected */
```

### Set up option selection

If the first argument begins with a '`-`', the user is choosing the desired counts and
specifying the order in which they should be displayed. Each selection is given by the
initial character (lines, words, or characters). For example, '`-cl`' would cause just
the number of characters and the number of lines to be printed, in that order. The
default, if no special argument is given, is '`-lwc`'.

We do not process this string now; we simply remember where it is. It will be used
to control the formatting at output time.

If the '`-`' is immediately followed by '`s`', only summary totals are printed.

```c
which = "lwc";    /* if no option is given, print all three values */
if (argc >1 && *argv[1] == '-') {
    argv[1]++;
    if (*argv [1] == 's') silent = 1, argv [1]++;
    if (*argv [1]) which = argv [1];
    argc--;
    argv++;
}
file_count = argc - 1;
```

### Process all the files

Now we scan the remaining arguments and try to open a file, if possible. The file
is processed and its statistics are given. We use a `do ... while` loop because
we should read from the standard input if no file name is given.

```c
argc--;
do {
    @{If a file is given, try to open *(++argv ); continue if unsuccessful}
    @{Initialize pointers and counters}
    @{Scan file}
    @{Write statistics for file}
    @{Close file}
    @{Update grand totals}
} while (--argc > 0);
```

Here’s the code to open the file. A special trick allows us to handle input from *stdin*
when no name is given. Recall that the file descriptor to *stdin* is `0`; that’s what we
use as the default initial value.

### Variables local to main +=

```c
int fd = 0;
```

### Preprocessor definitions +=

```c
#define READ_ONLY 0
```

### If a file is given, try to open *(++argv ); continue if unsuccessful

```c
if (file_count > 0 && (fd = open(*(++argv), READ_ONLY)) < 0) {
    fprintf(stderr, "%s: cannot open file %s\n", prog_name, *argv);
    status |= 2;
    file_count--;
    continue;
}
```

### Close file

```c
close(fd);
```

### Variables local to main +=

We will do some homemade buffering in order to speed things up: Characters will be
read into the buffer array before we process them. To do this we set up appropriate
pointers and counters.

```c
char buffer[BUFSIZ];    /* we read the input into this array */
register char *ptr;    /* the first unprocessed character in buffer */
register char *buf_end;    /* the first unused position in buffer */
register int c;    /* current character or number of characters just read */
int in_word;    /* are we within a word? */
long word_count, line_count, char_count;
    /* number of words, lines, and characters found in the file so far */
```

### Initialize pointers and counters

```c
ptr = buf_end = buffer;
line_count = word_count = char_count = 0;
in_word = 0;
```

### Global variables +=

The grand totals must be initialized to zero at the beginning of the program.
If we made these variables local to main, we would have to do this initialization explicitly;
however, C’s globals are automatically zeroed. (Or rather, "statically zeroed.") (Get it?)

```c
long tot_word_count, tot_line_count, tot_char_count;
    /* total number of words, lines and chars */
```

### Scan file

The present section, which does the counting that is `wc`'s *raison d'être*, was actually
one of the simplest to write. We look at each character and change state if it begins or ends a word.

```c
while (1) {
    @{Fill buffer if it is empty; break at end of file}
    c = *ptr++;
    if (c > ' ' && c < 177) {    /* visible ASCII codes */
        if (!in_word) {
            word_count++;
            in_word = 1;
        }
        continue;
    }
    if (c == '\n') line_count++;
    else if (c != ' ' && c != '\t') continue;
    in_word = 0;    /* c is newline, space, or tab */
}
```

### Fill buffer if it is empty; break at end of file

Buffered I/O allows us to count the number of characters almost for free.

```c
if (ptr >= buf_end) {
    ptr = buffer;
    c = read(fd, ptr, BUFSIZ);
    if (c <= 0) break;
    char_count += c;
    buf_end = buffer + c;
}
```

### Write statistics for file
It’s convenient to output the statistics by defining a new function `wc_print()`;
then the same function can be used for the totals. Additionally we must decide here
if we know the name of the file we have processed or if it was just *stdin*.

```c
if (!silent) {
    wc_print(which, char_count, word_count, line_count);
    if (file_count) printf(" %s\n", *argv);    /* not stdin */
    else printf("\n");    /* stdin */
}
```

### Update grand totals

```c
tot_line_count += line_count;
tot_word_count += word_count;
tot_char_count += char_count;
```

### Print the grand totals if there were multiple files

We might as well improve a bit on `UNIX`’s `wc` by displaying the number of files too.

```c
if (file_count > 1 || silent) {
    wc_print(which, tot_char_count, tot_word_count, tot_line_count);
    if (!file_count) printf("\n");
    else printf(" total in %d file%s\n", file_count, file_count > 1 ? "s" : "");
}
```

### Functions

Here now is the function that prints the values according to the specified options.
The calling routine is supposed to supply a newline. If an invalid option character
is found we inform the user about proper usage of the command. Counts are printed
in 8-digit fields so that they will line up in columns.

```c
void wc_print(char *which, long char_count, long word_count, long line_count)
{
    while (*which)
        switch (*which++) {
        case 'l': printf("%8ld", line_count);
            break;
        case 'w': printf("%8ld", word_count);
            break;
        case 'c': printf("%8ld", char_count);
            break;
        default:
            if ((status & 1) == 0) {
                fprintf(stderr, "\nUsage: %s [-lwc] [filename ...]\n", prog_name);
                status |= 1;
            }
        }
}
```
</details>
</summary>

**Comment by HomemadeToast57** [comment]
Wow! This is a very interesting concept! Currently, with a notebook, the output is shown below the block that reflects the code that printed that output, how would you track where it came from once you concatenate all blocks? Perhaps you can do something clever with comments? Perhaps looking at the runtime stack as well? I'd have to think of it a bit more. Is too far away from the direction you want HDNB to go? I feel like it _is_ possible. :)

**Comment by JacksonKearl** [comment]
In the proposed case, you'd only run the top level call and the output would be shown under that. In general the output should be shown under the cell that was triggered to execute, even if the actual print cell happens in a different cell. This is consistent with how other notebooks I'm aware of operate. 

HDNB core shouldn't know anything besides how to assemble cells into a code block, with the `dispatch` setting determining how to run those code blocks on the machine. 

This issue is asking for HDNB to additionally know how to write files, I'm still not sure that's something I'd like to support. I'd prefer providing a cell identifier that other scripts can use to write files, but if there's a big enough use case for it I'd consider it.

**Comment by HomemadeToast57** [comment]
Understood. Thanks for the response!

**Comment by JacksonKearl** [comment]
Implemented the code cell substitution, better tracked in #7.

**Comment by JacksonKearl** [comment]
`${code-path}` can now be used for the path to the cell's contents. I used this as follows:

runGcc.sh:
```
#!/bin/bash
gcc -xc "$1"
./a.out "$1" # using the cell file as the input to the program for this example
```

dispatch config:
```
    "c": [
      "./runGcc.sh",
      [
        "${code-path}"
      ]
    ]
```

code:

<summary> Knuthian WC<details>
# Word Count Program

Here, is an overview of the file `wc.c` that is defined by this Literate program:

```c
{{cell:Header files to include}}
{{cell:Preprocessor definitions}}
{{cell:Global variables}}
{{cell:Functions}}
{{cell:The main program}}
```

### Header files to include

We must include the standard I/O definitions, since we want to send formatted output to *stdout* and *stderr*.

```c
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
```

### Preprocessor definitions

We define various codes to represent different exist conditions of the program

```c
#define OK 1    /* status code for successful run */
#define usage_error 1    /* status code for improper syntax */
#define cannot_open_file 2    /* status code for file access error */
```

### Global variables
The `status` variable will tell the operating system if the run was successful or not,
and `prog_name` is used in case there’s an error message to be printed.

```c
int status = OK;    /* exit status of command, initially OK */
char *prog_name;    /* who we are */
```

### The main program

Now we come to the general layout of the `main()` function.

```c
int main(int argc, char **argv)
{
    {{cell:Variables local to main}}
    prog_name = argv[0];
    {{cell:Set up option selection}}
    {{cell:Process all the files}}
    {{cell:Print the grand totals if there were multiple files}}
    return status;
}
```

### Variables local to main

```c
int file_count;    /* how many files there are */
char *which;    /* which counts to print */
int silent = 0;    /* nonzero if the silent option was selected */
```

### Set up option selection

If the first argument begins with a '`-`', the user is choosing the desired counts and
specifying the order in which they should be displayed. Each selection is given by the
initial character (lines, words, or characters). For example, '`-cl`' would cause just
the number of characters and the number of lines to be printed, in that order. The
default, if no special argument is given, is '`-lwc`'.

We do not process this string now; we simply remember where it is. It will be used
to control the formatting at output time.

If the '`-`' is immediately followed by '`s`', only summary totals are printed.

```c
which = "lwc";    /* if no option is given, print all three values */
if (argc >1 && *argv[1] == '-') {
    argv[1]++;
    if (*argv [1] == 's') silent = 1, argv [1]++;
    if (*argv [1]) which = argv [1];
    argc--;
    argv++;
}
file_count = argc - 1;
```

### Process all the files

Now we scan the remaining arguments and try to open a file, if possible. The file
is processed and its statistics are given. We use a `do ... while` loop because
we should read from the standard input if no file name is given.

```c
argc--;
do {
    {{cell:If a file is given, try to open *(++argv ); continue if unsuccessful}}
    {{cell:Initialize pointers and counters}}
    {{cell:Scan file}}
    {{cell:Write statistics for file}}
    {{cell:Close file}}
    {{cell:Update grand totals}}
} while (--argc > 0);
```

Here’s the code to open the file. A special trick allows us to handle input from *stdin*
when no name is given. Recall that the file descriptor to *stdin* is `0`; that’s what we
use as the default initial value.

### Variables local to main +=

```c
int fd = 0;
```

### Preprocessor definitions +=

```c
#define READ_ONLY 0
```

### If a file is given, try to open *(++argv ); continue if unsuccessful

```c
if (file_count > 0 && (fd = open(*(++argv), READ_ONLY)) < 0) {
    fprintf(stderr, "%s: cannot open file %s\n", prog_name, *argv);
    status |= 2;
    file_count--;
    continue;
}
```

### Close file

```c
close(fd);
```

### Variables local to main +=

We will do some homemade buffering in order to speed things up: Characters will be
read into the buffer array before we process them. To do this we set up appropriate
pointers and counters.

```c
char buffer[BUFSIZ];    /* we read the input into this array */
register char *ptr;    /* the first unprocessed character in buffer */
register char *buf_end;    /* the first unused position in buffer */
register int c;    /* current character or number of characters just read */
int in_word;    /* are we within a word? */
long word_count, line_count, char_count;
    /* number of words, lines, and characters found in the file so far */
```

### Initialize pointers and counters

```c
ptr = buf_end = buffer;
line_count = word_count = char_count = 0;
in_word = 0;
```

### Global variables +=

The grand totals must be initialized to zero at the beginning of the program.
If we made these variables local to main, we would have to do this initialization explicitly;
however, C’s globals are automatically zeroed. (Or rather, "statically zeroed.") (Get it?)

```c
long tot_word_count, tot_line_count, tot_char_count;
    /* total number of words, lines and chars */
```

### Scan file

The present section, which does the counting that is `wc`'s *raison d'être*, was actually
one of the simplest to write. We look at each character and change state if it begins or ends a word.

```c
while (1) {
    {{cell:Fill buffer if it is empty; break at end of file}}
    c = *ptr++;
    if (c > ' ' && c < 177) {    /* visible ASCII codes */
        if (!in_word) {
            word_count++;
            in_word = 1;
        }
        continue;
    }
    if (c == '\n') line_count++;
    else if (c != ' ' && c != '\t') continue;
    in_word = 0;    /* c is newline, space, or tab */
}
```

### Fill buffer if it is empty; break at end of file

Buffered I/O allows us to count the number of characters almost for free.

```c
if (ptr >= buf_end) {
    ptr = buffer;
    c = read(fd, ptr, BUFSIZ);
    if (c <= 0) break;
    char_count += c;
    buf_end = buffer + c;
}
```

### Write statistics for file
It’s convenient to output the statistics by defining a new function `wc_print()`;
then the same function can be used for the totals. Additionally we must decide here
if we know the name of the file we have processed or if it was just *stdin*.

```c
if (!silent) {
    wc_print(which, char_count, word_count, line_count);
    if (file_count) printf(" %s\n", *argv);    /* not stdin */
    else printf("\n");    /* stdin */
}
```

### Update grand totals

```c
tot_line_count += line_count;
tot_word_count += word_count;
tot_char_count += char_count;
```

### Print the grand totals if there were multiple files

We might as well improve a bit on `UNIX`’s `wc` by displaying the number of files too.

```c
if (file_count > 1 || silent) {
    wc_print(which, tot_char_count, tot_word_count, tot_line_count);
    if (!file_count) printf("\n");
    else printf(" total in %d file%s\n", file_count, file_count > 1 ? "s" : "");
}
```

### Functions

Here now is the function that prints the values according to the specified options.
The calling routine is supposed to supply a newline. If an invalid option character
is found we inform the user about proper usage of the command. Counts are printed
in 8-digit fields so that they will line up in columns.

```c
void wc_print(char *which, long char_count, long word_count, long line_count)
{
    while (*which)
        switch (*which++) {
        case 'l': printf("%8ld", line_count);
            break;
        case 'w': printf("%8ld", word_count);
            break;
        case 'c': printf("%8ld", char_count);
            break;
        default:
            if ((status & 1) == 0) {
                fprintf(stderr, "\nUsage: %s [-lwc] [filename ...]\n", prog_name);
                status |= 1;
            }
        }
}
```

</details>
</summary>

Output:
```
     115     486    3253 /Users/jkearl/Library/Application Support/Code - Insiders/User/globalStorage/jakearl.handydandy-notebook/cells/618feb823fffbfd8ce1310a56db87311
```
